[WIP] Use `InferType` for type inference and drop usage of deprecated functions
ConsenSys/scribble pull request #200
Opened 2022-10-25 08:14 UTC by blitz-1306

2022-11-09 13:01 UTC, cd1m0 requested changes
Good work! All the @todos are on point. Taking lock on PR to work on these

2022-11-11 06:07 UTC, blitz-1306 commented on src/instrumenter/instrument.ts
> +    return node.getChildrenBySelector(
Well, it is actually the same as it was, with few twists... Literally, get childred, where:
- child is a `FunctionCall`
- child is not an instrumentation node (`typeString` is `<missing>`)
- child is an [external call by **solc-typed-ast**'s opinion](https://github.com/ConsenSys/solc-typed-ast/blob/ece08a453a562662b82431092695446ffec6b192/src/types/utils.ts#L351-L368)
- child function call refers to a user-defined function
  - or (if it is a builtin) is only refers to `call`, `delegatecall` or `staticcall` (due to **solc-typed-ast** considers [a borader list of builtins](https://github.com/ConsenSys/solc-typed-ast/blob/ece08a453a562662b82431092695446ffec6b192/src/types/utils.ts#L66) as external call candidates)

So, basically it is not that different than what we had before, except that is more compact.

2022-11-11 08:59 UTC, cd1m0 commented on src/instrumenter/instrument.ts
> +    return node.getChildrenBySelector(
Ok. Not strongly attached to changing it.

2022-11-28 06:34 UTC, blitz-1306 reviewed
Looks good. I would rebase other branch to see if we can bump coverage.

2022-11-28 07:28 UTC, blitz-1306 commented
I rebased #203. Test coverage there is passong required thresholds. We can ether merge it, or I can apply limited set of changes to this branch manually. WDYT?

2022-11-29 17:15 UTC, cd1m0 approved these changes

2022-11-29 17:15 UTC, merged