Cleanup in expr_grammar.pegjs and import_directive.pegjs
ConsenSys/scribble pull request #49
Opened 2021-05-26 11:29 UTC by blitz-1306

## Premise
For last few weeks Scribble received several bigger updates, that were affecting grammar. We figured out that it would be simplier to improve grammars and review them after making overall style a bit more readable.

## Changes
- Tweaked `import_directive.pegjs` and `expr_grammar.pegjs`:
  - [x] Tweaked indentation to consistently use 4 spaces instead of mixed `2` or `4`.
  - [x] Reduced nesting in macros.
  - [x] Conditional (ternary) operations in macros are now using same style `x === null ? undefined : x` instead of mixed cases.
  - [x] Equality sign now always appear in same line as th rule name (except `Keyword`s part).
  - [x] Expanded complex rules to utility multiline approach instead of too complicated single lines.

Regards.

2021-05-27 08:02 UTC, cd1m0 requested changes
Some nits

2021-05-27 08:02 UTC, cd1m0 commented on src/spec-lang/expr_grammar.pegjs
> +    (
Same here - rule on one line, code on the next line(s).

2021-05-27 12:30 UTC, blitz-1306 commented on src/spec-lang/expr_grammar.pegjs
> +    __ "("
Addressed in https://github.com/ConsenSys/scribble/pull/49/commits/3554091ae185b1e77d31f3b8930caae285aefee5

2021-05-27 12:30 UTC, blitz-1306 commented on src/spec-lang/expr_grammar.pegjs
> +    ("/" __)?
Addressed in https://github.com/ConsenSys/scribble/pull/49/commits/3554091ae185b1e77d31f3b8930caae285aefee5

2021-05-27 12:30 UTC, blitz-1306 commented on src/spec-lang/expr_grammar.pegjs
> +UserFunctionDefinition =
Addressed in https://github.com/ConsenSys/scribble/pull/49/commits/3554091ae185b1e77d31f3b8930caae285aefee5

2021-06-01 20:35 UTC, cd1m0 approved these changes
lgtm

2021-06-01 20:57 UTC, merged